name: Weather Alert for In Buri

on:
  workflow_dispatch:
  schedule:
    # แก้ไขบรรทัดนี้เพื่อรันทุกๆ 30 นาที
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weather script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: python weather_alert.py
